services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: terman_db
    ports:
      - "5435:5432"

  backend:
    build: ./backend
    command: ["/app/wait-for-postgres.sh", "bash", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      SECRET_KEY: sua-chave-secreta
      DATABASE_URL: postgresql://postgres:postgres@db:5432/terman_db
      ALLOWED_HOSTS: localhost,127.0.0.1

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000/api/v1

volumes:
  postgres_data:
    name: terman_postgres_data
