site_name: Terman OS
site_url: https://kallebyx.github.io/terman_os/
repo_url: https://github.com/KallebyX/terman_os
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    primary: deep orange
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  custom_dir: docs/overrides

nav:
  - Início: index.md
  - Instalação (dev): instalacao-dev.md
  - Deploy (Render): deploy.md
  - FAQ: faq.md
  - Equipe & Créditos: equipe.md
  - Contribuindo: ../CONTRIBUTING.md
  - Código de Conduta: ../CODE_OF_CONDUCT.md
  - Roadmap: ../ROADMAP.md

extra_css:
  - styles/terman.css

extra_javascript:
  - scripts/extra.js
