cat <<EOF > render.yaml
services:
  - type: web
    name: terman-os
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: terman-db
          property: connectionString
EOF